// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydflnpjndyowjkhaoabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZmxucGpuZHlvd2praGFvYWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEzODg4MjAsImV4cCI6MjA0Njk2NDgyMH0.Al5W6UeXyRrV21kfRvbaPTepHEZjr3_3-s-b26dLbVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);